### ISSUE TITLE
App stopped functioning, crashes when enabled

### ISSUE THREAD

**Issue by SquiggsWOW** [lkorth/photo-paper#2]
The application is crashing when Enabled in settings.    There appears to be an issue with the response from 500px.  I haven't had enough time to really look at the response, but my best guess is an expired or revoked API key.

logcat:
[2018-03-13-16-08-35.txt](https://github.com/lkorth/photo-paper/files/1808824/2018-03-13-16-08-35.txt)

**Comment by lkorth** [comment]
500px shut down their API 

>The history of 500px has always encouraged creative development, but as of January 24th 2018, 500px will no longer be offering free access to our API. This decision was made in order to protect our assets and improve our website's performance. On June 15th, access to the API will be shut down. This is part of a larger strategic shift—focusing our energy on continuing to build the world’s best photography community at 500px.com.

https://support.500px.com/hc/en-us/articles/360002435653-API-
